VirtoCommerce/vc-module-order

- VirtoCommerce.OrderModule.Data/Migrations/201609210923192_TotalsAndTaxesChanges.cs
> Fixing division by zero error

- VirtoCommerce.OrderModule.Web/Scripts/blades/customerOrder-list.tpl.html
Align price vertically in the middle in the orders list
> Price alignment fix

- VirtoCommerce.OrderModule.Data/Notifications/InvoiceEmailNotification.cs
- VirtoCommerce.OrderModule.Data/Notifications/NewOrderStatusEmailNotification.cs
- VirtoCommerce.OrderModule.Data/Notifications/OrderEmailNotificationBase.cs
- VirtoCommerce.OrderModule.Data/Notifications/OrderPaidEmailNotification.cs
- VirtoCommerce.OrderModule.Data/Observers/OrderNotificationObserver.cs
- VirtoCommerce.OrderModule.Data/VirtoCommerce.OrderModule.Data.csproj
- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
Throw if order not found, and assume GetNewNotification always returns a Notification object (it will throw otherwise).
> Reviewed code on method GetInvoicePdf

- VirtoCommerce.OrderModule.Data/Model/CustomerOrderEntity.cs
- VirtoCommerce.OrderModule.Data/Model/PaymentInEntity.cs
- VirtoCommerce.OrderModule.Data/Model/ShipmentEntity.cs
This PR extend & replace PR #3
> Fixed *Name properties update when db model must be updated

- VirtoCommerce.OrderModule.Data/Repositories/OrderRepositoryImpl.cs
Related to issue VirtoCommerce/vc-platform#1258
> Extend OrderRepositoryImpl with additional constructor

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
https://github.com/VirtoCommerce/vc-platform/issues/1386
> #1386 When update order with responseGroup:Default, the OrderModule is getting NullReferenceException

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
Added GetQueryable virtual method to have possibility to override Query.
> Made Query overridable.

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderBuilderImpl.cs
> #82 Remove CreatedDate

- VirtoCommerce.OrderModule.Test/CheckingResponseGroup.cs
- VirtoCommerce.OrderModule.Web/Security/OrderReadPricesPermission.cs
Issue #80 
Added response group check for an empty value.
Added test inline data.
> Added response group check for empty value.

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
> Paged search ordering revision

- VirtoCommerce.OrderModule.Web/Scripts/blades/filter-detail.js
- VirtoCommerce.OrderModule.Web/Scripts/order.js
Added possibility to customize filterDetail form using metaFormsService.registerMetaFields('orderFilterDetail',[…]).
> #103: Added possibility to customize filterDetail form using metaFormsService.registerMetaFields('orderFilterDetail',[…]).

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
- VirtoCommerce.OrderModule.Data/VirtoCommerce.OrderModule.Data.csproj
- VirtoCommerce.OrderModule.Data/packages.config
- VirtoCommerce.OrderModule.Test/VirtoCommerce.OrderModule.Test.csproj
- VirtoCommerce.OrderModule.Test/packages.config
- VirtoCommerce.OrderModule.Web/Scripts/blades/filter-detail.js
- VirtoCommerce.OrderModule.Web/Scripts/resources/securityAccounts.js
- VirtoCommerce.OrderModule.Web/VirtoCommerce.OrderModule.Web.csproj
- VirtoCommerce.OrderModule.Web/module.manifest
- VirtoCommerce.OrderModule.Web/packages.config
1. CustomerOrderService now can search by multiple customer ids;
2. Order filter converts contacts to acounts as customerIds before filtering.
> `customer` field now works on `orderFilterDetail` blade

- VirtoCommerce.OrderModule.Web/Content/css/orderModule.css
- VirtoCommerce.OrderModule.Web/Scripts/widgets/operation-tree-widget.tpl.html
copy tree styles frome core module
> fix operation-tree-widget scroll (independent from core module)

- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
- VirtoCommerce.OrderModule.Web/VirtoCommerce.OrderModule.Web.csproj
- VirtoCommerce.OrderModule.Web/packages.config
- VirtoCommerce.OrderModule.Web/web.config
Allowed Cors for CreateOrderFromCart method (for js shopping cart module).
> VP-729: Allowed Cors for CreateOrderFromCart method (for js shopping cart module).

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
- VirtoCommerce.OrderModule.Data/Services/DefaultCustomerOrderTotalsCalculator.cs
> CalculateTotals resets all totals in order

- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
- VirtoCommerce.OrderModule.Web/Security/OrderReadPricesPermission.cs
> check user is admin before search criteria filtration

- VirtoCommerce.OrderModule.Test/CheckingResponseGroup.cs
- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
- VirtoCommerce.OrderModule.Web/Security/OrderReadPricesPermission.cs
- Fixed the case when order prices are 0 for admin with some order permissions, but without "order:read_prices";
> VP-1048: Fix order prices visibility

- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
> vp-1126_move_CORS_manage_to_platform

- src/VirtoCommerce.OrdersModule.Data/Services/DefaultCustomerOrderTotalsCalculator.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- StoreId and Store filled properly when creating payments;
- Removed payment.Sum erasing in `CalculatePaymentTotals`;
Depends on https://github.com/VirtoCommerce/vc-module-payment/pull/4, need to update dependencies;
> VP-1310: Fix payments creation

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
Added check Shipments and InPayments collections of order for empty values
> Bug removed: VP-1501. Could not create customer order.

- VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs
Save all headers to ProcessPaymentEvaluationContext.parameters
> VP-1423 Send customer ip to authorize.net

- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
VP-2084 Don't show widget if user hasn't permission
> VP-2084 Don't show widget if user hasn't permission

- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
VP-2146 Don't show widget if a user hasn't permission
> VP-2146 Don't show widget if user hasn't permission

- src/VirtoCommerce.OrdersModule.Data/Handlers/CancelPaymentOrderChangedEventHandler.cs
Change payment status to Refunded after order has been canceled
> VP-2355 Change payment status to Refunded after order has been canceled

- VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs
Typo in variable.
Fix typo.
Fixed typo.
> Fix typo in CustomerOrderService

- src/VirtoCommerce.OrdersModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/CancelPaymentOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/LogChangesOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/SendNotificationsOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Web/JsonConverters/PolymorphicOperationJsonConverter.cs
- src/VirtoCommerce.OrdersModule.Web/package-lock.json
- tests/VirtoCommerce.OrdersModule.Tests/OrderInventoryAdjustmentTests.cs
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
> Optimisation: Remove DisableConcurrentExecution for some background jobs

- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-2853
> VP-2853: fix missing dependency

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.tpl.html
We need to be able to see comment for each LineItem in order
> VP-2834: Show LineItem comment in customerOrder-items blade

- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3120
> VP-3120: Set relative iconUrl

- .github/workflows/sync.yml
> VP-3187: Init CI

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-change-log.js
Fix script error caused by initialization order.
> VP-3496: Fix initialization order

- src/VirtoCommerce.OrdersModule.Data/Model/PaymentInEntity.cs
> VP-5040: Repair ability to remove billing address from payment in order

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-items.tpl.html
https://virtocommerce.atlassian.net/browse/VP-3592
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
> #VP-3592 show pager template when total more then per page count

- VirtoCommerce.OrderModule.Data/Model/PaymentInEntity.cs
- VirtoCommerce.OrderModule.Data/VirtoCommerce.OrderModule.Data.csproj
- VirtoCommerce.OrderModule.Data/packages.config
- VirtoCommerce.OrderModule.Test/VirtoCommerce.OrderModule.Test.csproj
- VirtoCommerce.OrderModule.Test/packages.config
- VirtoCommerce.OrderModule.Web/VirtoCommerce.OrderModule.Web.csproj
- VirtoCommerce.OrderModule.Web/module.manifest
- VirtoCommerce.OrderModule.Web/packages.config
VP-5178: ShipmentId Issue
ShipmentId always is null
Update core module dependence
Update convert method
> VP-5178: ShipmentId Issue

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
> #VP-5333 close children blades when save

- VirtoCommerce.OrderModule.Web/Scripts/blades/operation-detail.js
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
> #VP-1063 disable save

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
Total prices look broken sometimes on Admin > Orders. 
Reinitialize grid after permissions were updated.
> VP-5205: Incorrect view of total price

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
As we could have some info be filled only after saving to the database, and PrimaryKeyMap could not handle it, we need to build models from saved entities (which are in the actual state) for the new entries of event.
> VP-5561: Set actual model state in order event

- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderServiceImplIntegrationTests.cs
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderServiceUnitTests.cs
- Add tests for checking totals are calculated in ICustomerOrederService.SaveChanges();
- Fix integrations tests, but change database from default "virtocommerce3" to avoid unintended data modification;
> VP-5750: Add order totals unit tests

- src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html
Problem:
No shipment method option label in shipment blade.
Solution:
Add label.
Jira: https://virtocommerce.atlassian.net/browse/VP-2264
Resolves virtocommerce/vc-platform#1861
> VP-2264: feat add ShipmentMethodOption label

- src/VirtoCommerce.OrdersModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
- tests/VirtoCommerce.OrdersModule.Tests/OrderInventoryAdjustmentTests.cs
> VP-5826: In stock value doesn't changed on b2b

- src/VirtoCommerce.OrdersModule.Web/Authorization/OrderAuthorizationHandler.cs
There is a problem described [here](https://virtocommerce.atlassian.net/browse/VP-6222).
Employee contact with "order:read" grant with scope "Only for order responsible" can't see assigned orders only to him/her.
> VP-6222: Correct orders filtering by "Assigned to" selector

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html
Update shipping method selected in orders to use name field instead of typeName
> VP-6459: Shipment Type Not Using Name Correctly

- src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
- src/VirtoCommerce.OrdersModule.Data/Extensions/OperationExtensions.cs
- src/VirtoCommerce.OrdersModule.Data/Model/OperationEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/DefaultCustomerOrderTotalsCalculator.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
Fill Child Operations after recalculating order.
> VP-6457: Refresh Order Document Tree after changes

- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Model/PaymentInEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Model/ShipmentEntity.cs
- tests/VirtoCommerce.OrdersModule.Tests/OrderOperationPricePatchingTests.cs
- Fixed and refactored condition for determining whether order operation prices should be updated;
- Added tests;
> VP-6491: Fix shipment patch condition

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items-select.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items-select.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-items.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-items.tpl.html
> VP-6366: Replace panel action icons

- samples/VirtoCommerce.OrdersModule2.Web/Scripts/blades/invoice-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/resources/stores.js
- src/VirtoCommerce.OrdersModule.Web/module.manifest
!! store v3.10 release required !!
https://virtocommerce.atlassian.net/browse/VP-6749
> Fix vp 6749

- src/VirtoCommerce.OrdersModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
Move method out of the lambda function
> VP-6698: Product's "In stock" amount not changing after order

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
> VP-6645: Change fields grouping inside Settings blade of a Store

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
> VP-6864: Fix header icon

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Core/Notifications/OrderEmailNotificationBase.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/CancelPaymentOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/LogChangesOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/SendNotificationsOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
https://virtocommerce.atlassian.net/browse/PT-863
> PT-864: Fix: move order changes calc into handle to skip orders serialization in HangFire job

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
https://virtocommerce.atlassian.net/browse/PT-669
> PT-670: Fix filter icon

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.js
https://virtocommerce.atlassian.net/browse/PT-1040
> PT-1040 pass ProductType when opening order lineItem product details

- Directory.Build.props
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/JsonConverters/PolymorphicOperationJsonConverter.cs
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Make PolymorphicOperationJsonConverter descendant of platform's PolymorphJsonConverter in order to simplify code and use constructors caching.
https://virtocommerce.atlassian.net/browse/PT-1026
> PT-1027: Optimize PolymorphicOperationJsonConverter

- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModulePaymentsController.cs
https://virtocommerce.atlassian.net/browse/PT-1371
> PT-1371: Remove swagger validation smells

- src/VirtoCommerce.OrdersModule.Data/Migrations/20210512162446_AddOrderFulfillmentCenterId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20210512162446_AddOrderFulfillmentCenterId.cs
- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
https://virtocommerce.atlassian.net/browse/PT-830
> PT-1673 add FulfillmentCenter Id and Name to Line Item entity

- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderRepository.cs
https://virtocommerce.atlassian.net/browse/PT-2014
> PT-2016 switched to split queries in order repository

- src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderTests.cs
https://virtocommerce.atlassian.net/browse/PT-2065
> PT-2067 changed ShipmentItem-LineItem compare logic

- src/VirtoCommerce.OrdersModule.Core/Extensions/ConfigurationExtensions.cs
- src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderIndexedSearchCriteria.cs
- src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderIndexedSearchResult.cs
- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Core/Search/Indexed/IIndexedCustomerOrderSearchService.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Handlers/IndexCustomerOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderChangesProvider.cs
- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderDocumentBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderSearchRequestBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/IndexedCustomerOrderSearchService.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Module.cs
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/resources/customerOrders.js
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
- tests/VirtoCommerce.OrdersModule.Tests/VirtoCommerce.OrdersModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-2024
> PT-2027 add Order Indexation

- samples/VirtoCommerce.OrdersModule2.Web/Localizations/en.VirtoCommerce.Orders.json
- samples/VirtoCommerce.OrdersModule2.Web/Localizations/ru.VirtoCommerce.Orders.json
- samples/VirtoCommerce.OrdersModule2.Web/Scripts/order2.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
https://virtocommerce.atlassian.net/browse/PT-2143
> PT-2145: Add custom grid column for order extension

- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderDocumentBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
https://virtocommerce.atlassian.net/browse/PT-2678
https://virtocommerce.atlassian.net/browse/PT-2680
> PT-2678 Indexing StoreName and FFCname empty fields, workaround for index widget color

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
https://virtocommerce.atlassian.net/browse/PT-2382
https://virtocommerce.atlassian.net/browse/PT-2383
> PT-2765, PT-2766 Added refresh callback function; Manage order menu option

- samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Make store scope picker as a standard multiple selector
https://virtocommerce.atlassian.net/browse/PT-3496
> PT-3497: Make store scope picker as a standard multiple selector

- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Migrations/20210911072238_AddAddressOuterId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20210911072238_AddAddressOuterId.cs
- src/VirtoCommerce.OrdersModule.Data/Model/AddressEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
PT-4060: Extend Address with OuterId property
https://github.com/VirtoCommerce/vc-module-cart/pull/92
> PT-4060: Extend Address with OuterId property

- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderDocumentBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
> PT-2563 Index empty value for Boolean property with default 'False'

- src/VirtoCommerce.OrdersModule.Core/Model/CancelledState.cs
- src/VirtoCommerce.OrdersModule.Core/Model/OrderOperation.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/CancelPaymentOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20210915122904_AddCancelledStatae.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20210915122904_AddCancelledStatae.cs
- src/VirtoCommerce.OrdersModule.Data/Model/OperationEntity.cs
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
- tests/VirtoCommerce.OrdersModule.Tests/CancelPaymentOrderTests.cs
> PT-4300 Add CancelledState to Payment

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
> PT-3179: Skip rejected cart lineItems on making the order

- src/VirtoCommerce.OrdersModule.Web/Module.cs
Add missing possibility to resolve by ICrudService
https://virtocommerce.atlassian.net/browse/PT-5021
> PT-5021: Add missing possibility to resolve by ICrudService

- src/VirtoCommerce.OrdersModule.Web/Module.cs
> PT-4708: Register CustomerOrderService, CustomerOrderSearchService

- src/VirtoCommerce.OrdersModule.Web/Authorization/OrderAuthorizationHandler.cs
Fix bug to respect userId and memberId while  checking OnlyOrderResponsibleScope auth rule
https://virtocommerce.atlassian.net/browse/PT-6120
> Fix bug to respect userId and memberId in checking  auth rule

- src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20220112135938_AddFees.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20220112135938_AddFees.cs
- src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderBuilderUnitTests.cs
- tests/VirtoCommerce.OrdersModule.Tests/ZeroPrices.cs
Fee fields of the customer order are aligned with domain and DB models
https://virtocommerce.atlassian.net/browse/PT-5934
> PT-5934: New fee fields are added to the customer order

- .github/workflows/main.yml
- .github/workflows/publish_nugets.yml
- Directory.Build.props
- samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderDbContext.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModulePaymentsController.cs
- src/VirtoCommerce.OrdersModule.Web/Module.cs
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
- tests/VirtoCommerce.OrdersModule.Tests/VirtoCommerce.OrdersModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
> PT-1956: Bump .Net and EF up to 6

- src/VirtoCommerce.OrdersModule.Data/Handlers/SendNotificationsOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Null reference error is fixed in the send notification handler
https://virtocommerce.atlassian.net/browse/PT-6089
> PT-6089: Null reference error is fixed in the send notification handler

- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
> PT-6404: Fix empty sonar codecoverage report

- src/VirtoCommerce.OrdersModule.Data/Handlers/IndexCustomerOrderChangedEventHandler.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Partial search index update support
https://virtocommerce.atlassian.net/browse/PT-6527
> PT-6527: Partial search index update support

- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
> docs: Fix loc file

- src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
Comments are added to the customer order fields
https://virtocommerce.atlassian.net/browse/PT-7483
> PT-7483: Comments are added to the customer order fields

- Directory.Build.props
- src/VirtoCommerce.OrdersModule.Core/Model/Shipment.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20220614122254_AddShipmentTrackingInformation.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20220614122254_AddShipmentTrackingInformation.cs
- src/VirtoCommerce.OrdersModule.Data/Model/ShipmentEntity.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Tracking information fields are added to the shipment
https://virtocommerce.atlassian.net/browse/PT-7920
> PT-7920: Tracking information fields are added to the shipment

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
Simplify extending and customization of ConvertCartToOrder method.
https://virtocommerce.atlassian.net/browse/PT-7868
> PT-7868: Simplify extending and customization of ConvertCartToOrder method.

- Directory.Build.props
- src/VirtoCommerce.OrdersModule.Core/Services/IMemberOrdersService.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
- src/VirtoCommerce.OrdersModule.Web/Module.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Member order service for IsFirstTimeBuyer
https://virtocommerce.atlassian.net/browse/PT-5429
> PT-5429: Member order service for IsFirstTimeBuyer

- VirtoCommerce.OrdersModule.sln
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderServiceUnitTests.cs
https://virtocommerce.atlassian.net/browse/PT-8404
> PT-8404: Calculate totals for OldEntry in OrderChangedEvent

- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Use OutputJsonSerializerSettings when serializing search result
https://virtocommerce.atlassian.net/browse/PT-8520
> PT-8520: New fields not showing up in hamburger menu

- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
Add ability to update OuterId property value of LineItemEntity
> Update LineItemEntity OuterId in Patch method

- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderDbContext.cs
- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderRepository.cs
Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152
> PT-9152: Fix EF validation runtime warnings

- src/VirtoCommerce.OrdersModule.Data/Migrations/20221223154901_ChangeProductIdLength.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20221223154901_ChangeProductIdLength.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20221226121725_ChangeSkuLength.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20221226121725_ChangeSkuLength.cs
- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
> Change ProductId length from 64 to 128

- src/VirtoCommerce.OrdersModule.Core/Model/LineItem.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Migrations/20230124135725_AddLineItemVendorId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data/Migrations/20230124135725_AddLineItemVendorId.cs
- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-10299
> PT-10299: add VendorId to line item

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
https://virtocommerce.atlassian.net/browse/PT-11051
> PT-11051: adjust Inventory on Order cancellation

- src/VirtoCommerce.OrdersModule.Web/package-lock.json
- src/VirtoCommerce.OrdersModule.Web/package.json
- src/VirtoCommerce.OrdersModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
> PT-9395: add nodejs-lts support

- src/VirtoCommerce.OrdersModule.Web/Authorization/OrderAuthorizationHandler.cs
https://virtocommerce.atlassian.net/browse/PT-11083
> PT-11083: User must have permissions to access orders

- samples/VirtoCommerce.OrdersModule2.Web/Scripts/blades/invoice-detail.js
- samples/VirtoCommerce.OrdersModule2.Web/Scripts/blades/invoice-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html
https://virtocommerce.atlassian.net/browse/PT-11234
> PT-11234: Assign any employee as responsible

- src/VirtoCommerce.OrdersModule.Data/Model/RefundEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-add.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-detail.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/services/refundReasons.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/widgets/operation-tree-widget.js
https://virtocommerce.atlassian.net/browse/PT-11270
https://virtocommerce.atlassian.net/browse/PT-11336
> PT-11270, PT-11336: display refund message and refund reason, add delete refund document

- src/VirtoCommerce.OrdersModule.Core/Model/LineItem.cs
- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230406145631_AddOrderLineItemStatus.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230406145631_AddOrderLineItemStatus.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230406145645_AddOrderLineItemStatus.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230406145645_AddOrderLineItemStatus.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230406145524_AddOrderLineItemStatus.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230406145524_AddOrderLineItemStatus.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.tpl.html
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderBuilderUnitTests.cs
https://virtocommerce.atlassian.net/browse/PT-11621
> PT-11621: Extend order line item with status

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
Use new cart properties in CustomerOrderBuilder
> Use comment from cart shipments and payments

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/Services/DefaultCustomerOrderTotalsCalculator.cs
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderServiceImplIntegrationTests.cs
- tests/VirtoCommerce.OrdersModule.Tests/OrderTotalsCalculationTest.cs
- Fix shipment fee in order builder
- Fix order total with fees in DefaultCustomerOrderTotalsCalculator
> Fix order fee calculations

- src/VirtoCommerce.OrdersModule.Core/Model/Refund.cs
- src/VirtoCommerce.OrdersModule.Core/Model/RefundOrderPaymentRequest.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230504164555_AddTransactionId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230504164555_AddTransactionId.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230510123916_ChangeOrderRefundDeleteBehavior.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230510123916_ChangeOrderRefundDeleteBehavior.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230504163400_AddTransactionId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230504163400_AddTransactionId.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230510124005_ChangeOrderRefundDeleteBehavior.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20230510124005_ChangeOrderRefundDeleteBehavior.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230504162915_AddTransactionId.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230504162915_AddTransactionId.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230510122621_ChangeOrderRefundDeleteBehavior.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20230510122621_ChangeOrderRefundDeleteBehavior.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data/Model/RefundEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderDbContext.cs
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-add.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-add.js
https://virtocommerce.atlassian.net/browse/PT-12013
> PT-12013: Extend Refund API with Transaction Correlation Id

- src/VirtoCommerce.OrdersModule.Web/Authorization/OrderAuthorizationHandler.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleShipmentsController.cs
https://virtocommerce.atlassian.net/browse/PT-11421
> PT-11421: Add permission scopes authorization for delete operation

- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
https://virtocommerce.atlassian.net/browse/PT-12244
> PT-12244: UpdateOrder - check original order in authorization handler

- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModulePaymentsController.cs
fix: Rest API returns Unauthorized instead of Forbid.
https://virtocommerce.atlassian.net/browse/PT-12269
> PT-12269: Rest API returns Unauthorized instead of Forbid.

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
https://virtocommerce.atlassian.net/browse/PT-12229
> PT-12229: remove capture fix

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
> PT-12327: change cancel operation canExecuteMethod

- .github/workflows/module-ci.yml
- src/VirtoCommerce.OrdersModule.Core/Model/Capture.cs
- src/VirtoCommerce.OrdersModule.Core/Model/CaptureStatus.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
feat: Add HandleConcurrentUpdate and Retry Policy for Capture and Refund.
https://virtocommerce.atlassian.net/browse/PT-12607
> PT-12607: Add Handle Concurrent Update and Retry Policy for Capture and Refund

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderBuilderUnitTests.cs
https://virtocommerce.atlassian.net/browse/PT-11577
> PT-11577: add InitialProcessingStatus

- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderSearchRequestBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13124
> PT-13124: Fix search criteria corruption

- src/VirtoCommerce.OrdersModule.Core/Model/PaymentDistributedLockOptions.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModulePaymentsController.cs
- src/VirtoCommerce.OrdersModule.Web/Module.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
> PT-12665: Add distributed lock service

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
fix: UI disabled when user try to create payment/shipment document
https://virtocommerce.atlassian.net/browse/PT-13216
> PT-13216: UI disabled when user try to create payment/shipment document

- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderDocumentBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-13046
> PT-13046: Implement IIndexSchemaBuilder

- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderDocumentBuilder.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Module.cs
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
feat: Extend filter blade with "With templates" filter to display order templates.
fix: Add IsPrototype to full-text document.
fix: Error when request Order Template by Id
https://virtocommerce.atlassian.net/browse/PT-13333
> PT-13333: IsPrototype is missing

- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Repositories/OrderDbContext.cs
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.
https://virtocommerce.atlassian.net/browse/PT-13179
> PT-13179: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.

- Directory.Build.props
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-13365
> PT-13365: selected for checkout

- src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20231018130044_IsAnonymous.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20231018130044_IsAnonymous.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20231018130007_IsAnonymous.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20231018130007_IsAnonymous.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20231018125853_IsAnonymous.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20231018125853_IsAnonymous.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13935
> PT-13935: add IsAnonyomus to customer order

- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
https://virtocommerce.atlassian.net/browse/PT-14000
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.417.0-pr-384-426b.zip
> PT-14000: handle null Store in payment/shipment blade

- src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
fix: Capture and Refund should be repeatable with same transaction id if Status is Pending
https://virtocommerce.atlassian.net/browse/PT-14280
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.418.0-pr-385-9958.zip
> PT-14280: Pending Capture and Refund should be repeatable

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-detail.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/services/statusTranslation.js
- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-13976
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.421.0-pr-389-31f8.zip
> PT-13976: Add localization to order statuses

- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs
https://virtocommerce.atlassian.net/browse/PT-14487
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.425.0-pr-392-13d8.zip
> PT-14487: load payment and shipment types when raise event

- src/VirtoCommerce.OrdersModule.Core/Model/Search/ShipmentSearchCriteria.cs
- src/VirtoCommerce.OrdersModule.Core/Model/Search/ShipmentSearchResult.cs
- src/VirtoCommerce.OrdersModule.Core/Services/IShipmentSearchService.cs
- src/VirtoCommerce.OrdersModule.Data/Model/ShipmentEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/PaymentSearchService.cs
- src/VirtoCommerce.OrdersModule.Data/Services/ShipmentSearchService.cs
- src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleShipmentsController.cs
- src/VirtoCommerce.OrdersModule.Web/Module.cs
feat: Add Shipment Search Service (IShipmentSearchService) and Rest API (api/order/shipments) to create, search, get and delete shipment by id.
https://virtocommerce.atlassian.net/browse/PT-14675
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.426.0-pr-394-4c8b.zip
> PT-14675: Add Shipment Search Service

- Directory.Build.props
- samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data.MySql/VirtoCommerce.OrdersModule.Data.MySql.csproj
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/VirtoCommerce.OrdersModule.Data.PostgreSql.csproj
- src/VirtoCommerce.OrdersModule.Data.SqlServer/VirtoCommerce.OrdersModule.Data.SqlServer.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/VirtoCommerce.OrdersModule.Web.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
- tests/VirtoCommerce.OrdersModule.Tests/CancelPaymentOrderTests.cs
- tests/VirtoCommerce.OrdersModule.Tests/LogChangesOrderTests.cs
- tests/VirtoCommerce.OrdersModule.Tests/VirtoCommerce.OrdersModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.800.0-pr-391-8bf0.zip
> PT-14740: .net 8

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
https://virtocommerce.atlassian.net/browse/VCST-156
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.801.0-pr-396-9974.zip
> VCST-156: send current criteria to order list parent refresh function

- samples/VirtoCommerce.OrdersModule2.Web/Scripts/tree-template.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/widgets/operation-tree-widget.tpl.html
fix: The form of the new shipment, payment  document contains the value in the Date and time field 1 of January.
https://virtocommerce.atlassian.net/browse/VCST-683
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.809.0-pr-411-2050.zip
> VCST-683: Date in new shipment payment documents

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
* set CreatedDate to null if it quals to min Date
https://virtocommerce.atlassian.net/browse/VCST-774
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.814.0-pr-416-4fde.zip
> VCST-774: fix empty date problem

- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20240531125743_ResizeAddressFields.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20240531125743_ResizeAddressFields.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20240531125842_ResizeAddressFields.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20240531125842_ResizeAddressFields.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20240531125923_ResizeAddressFields.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20240531125923_ResizeAddressFields.cs
- src/VirtoCommerce.OrdersModule.Data/Model/AddressEntity.cs
- Resize AddressEntity fields according to customer AddressEntity fields
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.816.0-pr-418-f75b.zip
> feat: Resize address fields according to customer address fields

- .github/workflows/module-sample-ci.yml
- src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
fix: Resolves the issue when CreateOrderFromCart mutation returns null Payment Status.
https://virtocommerce.atlassian.net/browse/VCST-1343
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.817.0-pr-419-3ff7.zip
> VCST-1343: Null Payment Status

- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20240610080959_AddressDescription.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20240610080959_AddressDescription.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Readme.md
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20240610081022_AddressDescription.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20240610081022_AddressDescription.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Readme.md
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20240610080923_AddressDescription.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20240610080923_AddressDescription.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Readme.md
- src/VirtoCommerce.OrdersModule.Data/Model/AddressEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
fix: The description field is reset in Addresses blade
https://virtocommerce.atlassian.net/browse/VCST-1090
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.820.0-pr-422-0c9a.zip
> VCST-1090: The description field is reset in Addresses blade

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
feat: Add routes for order. It helps manage orders better, makes it easier to search for order by ID, and allows us to copy order link.
https://virtocommerce.atlassian.net/browse/VCST-1514
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.823.0-pr-425-8b3f.zip
[VCST-1514]: https://virtocommerce.atlassian.net/browse/VCST-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VCST-1514: Routes for orders

- src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.tpl.html
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/operation-detail.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
feat: Quick Orders Filters by Customer, Organization and Store.
feat: Improve Order filter panel UX
feat: Extends the filter details with filter by organization.
https://virtocommerce.atlassian.net/browse/VCST-1526
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.823.0-pr-426-296d.zip
> VCST-1526: Quick Orders Filters

- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
https://virtocommerce.atlassian.net/browse/VCST-1619
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.824.0-pr-427-3572.zip
> fix: Fix 401 error on sign in page

- src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
https://virtocommerce.atlassian.net/browse/VCST-1631
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.825.0-pr-428-736e.zip
> VCST-1631: set correct blade id

- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js
- src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
feat:  Implemented default relevance sorting for keyword searches. This enhancement ensures that search results are more relevant to the user's query. The next click in the grid enables custom sorting for the search results.
https://virtocommerce.atlassian.net/browse/VCST-1856
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.828.0-pr-432-4a16.zip
> VCST-1856: Search by keyword use relevance sorting by default

- Directory.Build.props
- src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data/Search/Indexed/IndexedCustomerOrderSearchService.cs
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1454
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.829.0-pr-433-32ca.zip
> VCST-1454: add relevance score to CustomerOrder

- src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderSearchCriteria.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderSearchService.cs
feat: Added the ability to search for orders by the included product
https://virtocommerce.atlassian.net/browse/VCST-1924
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.832.0-pr-434-59df.zip
> VCST-1924: Ability to search for orders by the product

- samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data.MySql/VirtoCommerce.OrdersModule.Data.MySql.csproj
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/VirtoCommerce.OrdersModule.Data.PostgreSql.csproj
- src/VirtoCommerce.OrdersModule.Data.SqlServer/VirtoCommerce.OrdersModule.Data.SqlServer.csproj
- src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
- src/VirtoCommerce.OrdersModule.Web/Authorization/OrderAuthorizationHandler.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
feat: Replace custom code with ClaimsPrincipalExtensions that resolves user id and name from IdentityOptions settings.
https://virtocommerce.atlassian.net/browse/VCST-2048
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.833.0-pr-437-c4f4.zip
> VCST-2048: Use ClaimsPrincipalExtensions GetUserId

- src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241108155732_OrderPromotionName.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241108155732_OrderPromotionName.cs
- src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241108155806_OrderPromotionName.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241108155806_OrderPromotionName.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241108155834_OrderPromotionName.Designer.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241108155834_OrderPromotionName.cs
- src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
- src/VirtoCommerce.OrdersModule.Data/Model/DiscountEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
- src/VirtoCommerce.OrdersModule.Web/module.manifest
- tests/VirtoCommerce.OrdersModule.Tests/CustomerOrderServiceImplIntegrationTests.cs
feat: Added "PromotionName" column to DiscountEntity
https://virtocommerce.atlassian.net/browse/VCST-1659
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.835.0-pr-439-c375.zip
> * VCST-1659: Added "PromotionName" column to DiscountEntity

- src/VirtoCommerce.OrdersModule.Data/Handlers/CancelPaymentOrderChangedEventHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-2080
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.842.0-pr-445-572f.zip
> VCST-2080: change payment document status

- src/VirtoCommerce.OrdersModule.Core/Model/ConfigurationItem.cs
- src/VirtoCommerce.OrdersModule.Core/Model/ConfigurationItemFile.cs
- src/VirtoCommerce.OrdersModule.Data/Model/ConfigurationItemEntity.cs
- src/VirtoCommerce.OrdersModule.Data/Model/ConfigurationItemFileEntity.cs
fix: Removed LineItemId and ConfigurationItemId properties from ConfigurationItem, ConfigurationItemFile, and their respective entity classes.
https://virtocommerce.atlassian.net/browse/VCST-3755
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.854.0-pr-461-26aa.zip
> VCST-3755: Refactor configuration item and file relationships

- src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
feat: Enable event-based indexation by default
https://virtocommerce.atlassian.net/browse/VCST-4016
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.858.0-pr-468-c10f.zip
> VCST-4016: Enable event-based indexation by default
