VirtoCommerce.OrderModule.Data/Observers/LogOrderChangesObserver.cs

The AutoCompare library's Difference class contains a bug in the implementation of the GetHashCode method, it throws a NullReferenceException if one of it's properties has a null value. This causes an exception when the Distinct method in called on line 100, and the collection differences contain some null value.

Fix exception in LogOrderChangesObserver.cs

---

VirtoCommerce.OrderModule.Data/Model/AddressEntity.cs

@tatarincev The mapping for Organization is missing from the Order Address entity patch.

Patch missing Organization mapping

---

VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs

This PR is a part of the VirtoCommerce/vc-module-cart#28 and fixes Swagger validation error with message `Equivalent paths are not allowed.` This error was caused by multiple `OrderModuleController` methods having similar (but not equal) routes:
* `OrderModuleController.GetById` available by GET at `api/order/customerOrders/{id}`;
* `OrderModuleController.CreateOrderFromCart` available by POST at `api/order/customerOrders/{cartId}`.
This caused Swashbuckle to create multiple entries with similar paths, and it caused Swagger validation to fail.
To solve this issue, I've renamed the parameter of the `CreateOrderFromCart` to `id`. Now `GetById` and `CreateOrderFromCart` are both available at `api/order/customerOrders/{id}`, and Swashbuckle groups them to one entry. Note that HTTP methods are …

CartModule, 28: renamed controller method parameter to eliminate Swagger operation path conflict

---

VirtoCommerce.OrderModule.Data/App.config
VirtoCommerce.OrderModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
VirtoCommerce.OrderModule.Data/VirtoCommerce.OrderModule.Data.csproj
VirtoCommerce.OrderModule.Data/packages.config
VirtoCommerce.OrderModule.Test/OrderInventoryAdjustmentTests.cs
VirtoCommerce.OrderModule.Test/VirtoCommerce.OrderModule.Test.csproj
VirtoCommerce.OrderModule.Test/packages.config
VirtoCommerce.OrderModule.Web/Module.cs
VirtoCommerce.OrderModule.Web/module.manifest

Changes made there for #69:
* Added reference to the `Hangfire.Core` for the `VirtoCommerce.OrdersModule.Data` project (to use it for background jobs);
* `AdjustInventoryOrderEventHandler`: inventory adjustment now runs in Hangfire task with disabled concurrency;
* `AdjustInventoryOrderEventHandler.TryAdjustOrderInventory` now takes actual data needed for inventory adjustment: change type, order ID, order shipments and line item lists (old and new one). This was needed because Hangfire with it's default serialization settings can't deserialize `GenericChangedEntry<CustomerOrder>` (because of missing default constructor), nor the `CustomerOrder` itself (because of polymorphic `IOperation` implementations).

69: concurrency fix for inventory adjustment

---

VirtoCommerce.OrderModule.Data/Handlers/AdjustInventoryOrderChangedEventHandler.cs
VirtoCommerce.OrderModule.Web/JsonConverters/PolymorphicOperationJsonConverter.cs
VirtoCommerce.OrderModule.Web/Module.cs

Without that serialize adjust inventory background job fails with "unable to cast" exception if you trying override ProductInventoryChange

Fixed bug which prevent override ProductInventoryChange

---

src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderHistorySearchCriteria.cs
src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-change-log.js
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-change-log.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/resources/customerOrders.js
src/VirtoCommerce.OrdersModule.Web/Scripts/widgets/customerOrder-change-log-widget.js

VP-3496: Add pagination to order changes blade
* Add method to a controller to search order changes
* Add infinite scrolling to order changes blade
Can't see more than 20 items in order changes blade 
Add pagination to order history blade

bug/VP-3496: Add pagination to order history blade

---

src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs

Without filled ShoppingCartId subscriptions are not created at all. Before they were created as there was no entity.ToModel conversion.

VP-5561: Add missing ShoppingCartId filling in entity/model conversions

---

src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs

With the changes introduces in #195 , newly created model lacks calculated fields. It was a breaking change, because before NewEntry had totals.
This PR runs missed totals calculation for NewEntry

VP-5750: Add totals calculation for new model in Changed event

---

src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.js
src/VirtoCommerce.OrdersModule.Web/Scripts/resources/accessToPricing.js
src/VirtoCommerce.OrdersModule.Web/module.manifest

This contribution inspired by performing devlab issue DL-60.
Dependency on the pricing module removed.
If there is no pricing module installed, lineitems added thru admin UI with zero prices.
https://virtocommerce.atlassian.net/browse/DL-60

DL-60: Remove pricing dependency

---

src/VirtoCommerce.OrdersModule.Core/Model/CustomerOrder.cs
src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs
src/VirtoCommerce.OrdersModule.Data/Repositories/IOrderRepository.cs
src/VirtoCommerce.OrdersModule.Data/Repositories/OrderRepository.cs
src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs

fix: Incorrect work with order, when 2 users try to update one order.
Added RowVersion to API model and error handling for DbUpdateConcurrencyException:
https://virtocommerce.atlassian.net/browse/PT-12311

PT-12311: Incorrect work with order, when 2 users try to update one order

---

src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderSearchCriteria.cs
src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderSearchService.cs

fix: OrganizationId and OrganizationIds are missed in CustomerOrderSearchCriteria
https://virtocommerce.atlassian.net/browse/PT-12481

PT-12481: OrganizationId and OrganizationIds are missed in CustomerOrderSearchCriteria

---

src/VirtoCommerce.OrdersModule.Web/Module.cs

fix: VirtoCommerce.OrdersModule.Core.Model.Capture not showing in dynamic properties list
https://virtocommerce.atlassian.net/browse/PT-13194

PT-13194: Capture not showing in dynamic properties list

---

src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs

fix: Missing BeforeSaveChanges and AfterSaveChangesAsync methods on SaveChangesAsync.
https://virtocommerce.atlassian.net/browse/PT-13270

PT-13270: Missing BeforeSaveChanges and AfterSaveChangesAsync on SaveChangesAsync

---

src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-items.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/refund-detail.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/shipment-detail.tpl.html

https://virtocommerce.atlassian.net/browse/PT-13514

PT-13514: bind current value directly in ui-select-match

---

src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/order.js

feat: Allows to Update and Retry Rejected Capture document with same Transaction Id.
feat: Allows to Update and Retry Rejected Refund document  with same Transaction Id.
feat: Added Transaction Id and Outer Id on Capture details blade.
feat: Added Transaction Id and Outer Id on Refund details blade.
https://virtocommerce.atlassian.net/browse/PT-13737

PT-13737: Allows to Update and Retry Rejected Capture and Rufund documents

---

src/VirtoCommerce.OrdersModule.Core/ModuleConstants.cs
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json

https://virtocommerce.atlassian.net/browse/PT-13757

PT-13757: add missing localization strings

---

src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js

use default search or indexed search
https://virtocommerce.atlassian.net/browse/PT-13362
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.419.0-pr-386-1027.zip

PT-13362: use default search or indexed search

---

src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs

- Check vendors from selected cart items for shipments and payments during order creation
How to reproduce the bug:
1. Add two (or more) vendors to the cart
2. Go to the checkout process
3. Choose the payment method for (all) vendors
4. Return to the cart unselect in the cart Vendor1 and go to the checkout process (checkbox only on Vendor2)
5. Place Order > The order is successfully created
6. Payments and shipments are created for all vendors in the created order
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.420.0-pr-387-a43d.zip

fix: Check vendors from selected cart items for shipments and payments

---

src/VirtoCommerce.OrdersModule.Core/Model/Capture.cs
src/VirtoCommerce.OrdersModule.Core/Model/CaptureOrderPaymentRequest.cs
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20231204102834_CloseTransaction.Designer.cs
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20231204102834_CloseTransaction.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20231204102736_CloseTransaction.Designer.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20231204102736_CloseTransaction.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20231204102652_CloseTransaction.Designer.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20231204102652_CloseTransaction.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Readme.md
src/VirtoCommerce.OrdersModule.Data/Model/CaptureEntity.cs
src/VirtoCommerce.OrdersModule.Data/Services/PaymentFlowService.cs
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/capture-add.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/capture-add.js
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/capture-detail.html
src/VirtoCommerce.OrdersModule.Web/package-lock.json

feat: Add optional Close Transaction property for Capture. Set to True to close a transaction, restricting future capture operations against this order; otherwise, set to False. By default, False. A payment provider can implement own support for it.
https://virtocommerce.atlassian.net/browse/PT-14571
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.423.0-pr-390-b256.zip

PT-14571: Extend Capture with CloseTransaction property

---

src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
src/VirtoCommerce.OrdersModule.Web/module.manifest

fix: Organization Name is empty
Please note that this release does not update the OrganizationName in the Cart and Order entities in the database. To update these entities, you can use the script provided below. The script updates the OrganizationName in the Cart and CustomerOrder tables by joining it with the Member table on the Id in Member and OrganizationId. 
> If you store Cart, CustomerOrder, and Member in different databases, you will need to modify the script accordingly.
```sql
-- SqlServer Script
UPDATE Cart SET OrganizationName = m.[Name] FROM Cart c
JOIN Member m ON c.OrganizationId = m.Id AND c.Type IS NULL
UPDATE CustomerOrder SET OrganizationName = m.[Name] FROM Cart c
JOIN Member m ON c.OrganizationId = m.Id
```
https://virtocommerce.atlassian.net/browse/PT-14655 …

PT-14655: Organization Name is empty

---

src/VirtoCommerce.OrdersModule.Core/Model/Search/CustomerOrderIndexedSearchCriteria.cs
src/VirtoCommerce.OrdersModule.Core/Search/Indexed/IIndexedCustomerOrderSearchService.cs
src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderSearchRequestBuilder.cs
src/VirtoCommerce.OrdersModule.Data/Search/Indexed/FilterHelper.cs
src/VirtoCommerce.OrdersModule.Data/Search/Indexed/IndexedCustomerOrderSearchService.cs
src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js

fix: The fix resolves that filter in orders blade doesn't work with indexing search.
feat: Enhancement to the data retrieval process by utilizing the api/order/customerOrders/search endpoint. Instead of relying on indexing search during data loading without specific filters, this update ensures more efficient access to non-indexed data, particularly when indexation is still in progress.
https://virtocommerce.atlassian.net/browse/VCST-204
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.802.0-pr-398-4644.zip

VCST-204: Filter in Orders blade doesn't work with indexing search

---

src/VirtoCommerce.OrdersModule.Web/Scripts/blades/capture-detail.html
src/VirtoCommerce.OrdersModule.Web/Scripts/order.js

feat: The Close Transaction switcher in the Capture document is now disabled for editing. It is preventing any unintended effects on the Payment provider.
https://virtocommerce.atlassian.net/browse/VCST-398
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.805.0-pr-405-2ec1.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.805.0-pr-405-aa80.zip

VCST-398: Close Transaction switcher in Capture document should not be active for editing

---

src/VirtoCommerce.OrdersModule.Data/Services/PaymentService.cs

execute clear cache for payments
https://virtocommerce.atlassian.net/browse/VCST-461
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.806.0-pr-406-c0e6.zip

clear cache

---

src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.js
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-detail.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.OrdersModule.Web/Scripts/resources/securityAccounts.js
src/VirtoCommerce.OrdersModule.Web/module.manifest

feat: Set of back office improvements to support Order Manager Role with limited permission.
fix: OrganizationId not found error.
fix: Extra padding on order details blade.
fix: Eliminate usage of securityAccount service.
fix: Eliminate requirement to add platform:security:read permission into Order Manager Role.
https://virtocommerce.atlassian.net/browse/VCST-630
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.807.0-pr-408-cdd2.zip

VCST-630: Order Manager Role Improvements

---

src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.js

https://virtocommerce.atlassian.net/browse/VCST-664
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.810.0-pr-413-dbef.zip

VCST-664: add predefined filters

---

src/VirtoCommerce.OrdersModule.Data/Search/Indexed/CustomerOrderSearchRequestBuilder.cs
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html
src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
src/VirtoCommerce.OrdersModule.Web/Scripts/widgets/customerOrder-list-widget.js
src/VirtoCommerce.OrdersModule.Web/Scripts/widgets/customerOrder-list-widget.tpl.html

---
https://virtocommerce.atlassian.net/browse/VCST-1482
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.822.0-pr-424-029d.zip

VCST-1482: add orders widget to customer and organization blade

---

src/VirtoCommerce.OrdersModule.Web/Controllers/Api/OrderModuleController.cs

https://virtocommerce.atlassian.net/browse/VCST-1754
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.827.0-pr-431-1793.zip

VCST-1754: Add missing authorization to some endpoints

---

src/VirtoCommerce.OrdersModule.Web/Scripts/blades/customerOrder-list.tpl.html

Put context menu for order list to a separate template, so it can be extended/modified in client projects
https://virtocommerce.atlassian.net/browse/VCST-2110
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.831.0-pr-435-61c7.zip

feat: move context menu to separated template

---

src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241104115901_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241104115901_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241104115928_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241104115928_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/OrderDbContextModelSnapshot.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241104115949_RemoveRequiredFromAddressFields.Designer.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241104115949_RemoveRequiredFromAddressFields.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/OrderDbContextModelSnapshot.cs
src/VirtoCommerce.OrdersModule.Data/Model/AddressEntity.cs

Removed required attribute for address LastName and FirstName, because in customer module this attribute already removed for member address (https://github.com/VirtoCommerce/vc-module-customer/blob/dev/src/VirtoCommerce.CustomerModule.Data/Model/AddressEntity.cs)
Connected to - https://github.com/VirtoCommerce/vc-module-cart/pull/154
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.834.0-pr-438-7067.zip

Remove Required attribute from FirstName and LastName in AddressEntity

---

samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
src/VirtoCommerce.OrdersModule.Core/Model/ConfigurationItem.cs
src/VirtoCommerce.OrdersModule.Core/Model/LineItem.cs
src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241121125717_AddConfigurationItems.Designer.cs
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20241121125717_AddConfigurationItems.cs
src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/OrderDbContextModelSnapshot.cs
src/VirtoCommerce.OrdersModule.Data.MySql/VirtoCommerce.OrdersModule.Data.MySql.csproj
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241121125805_AddConfigurationItems.Designer.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/Migrations/20241121125805_AddConfigurationItems.cs
src/VirtoCommerce.OrdersModule.Data.PostgreSql/VirtoCommerce.OrdersModule.Data.PostgreSql.csproj
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241121082404_AddConfigurationItems.Designer.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/Migrations/20241121082404_AddConfigurationItems.cs
src/VirtoCommerce.OrdersModule.Data.SqlServer/VirtoCommerce.OrdersModule.Data.SqlServer.csproj
src/VirtoCommerce.OrdersModule.Data/Model/ConfigurationItemEntity.cs
src/VirtoCommerce.OrdersModule.Data/Model/LineItemEntity.cs
src/VirtoCommerce.OrdersModule.Data/Repositories/OrderDbContext.cs
src/VirtoCommerce.OrdersModule.Data/Repositories/OrderRepository.cs
src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderBuilder.cs
src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
src/VirtoCommerce.OrdersModule.Web/module.manifest
tests/VirtoCommerce.OrdersModule.Tests/VirtoCommerce.OrdersModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/VCST-2092
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.836.0-pr-440-352f.zip

VCST-2092: add ConfigurationItemEntity

---

src/VirtoCommerce.OrdersModule.Web/Localizations/de.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/en.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/es.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/fr.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/it.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/ja.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/pl.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/pt.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/ru.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Localizations/zh.VirtoCommerce.Orders.json
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.js
src/VirtoCommerce.OrdersModule.Web/Scripts/blades/payment-detail.tpl.html
src/VirtoCommerce.OrdersModule.Web/module.manifest
src/VirtoCommerce.OrdersModule.Web/package-lock.json

fix: Reorganized and reformatted JSON files for multiple locales (de, en, es, fr, it, ja, pl, pt, ru, zh) to ensure consistency and completeness of order management information.
fix: Updated `payment-detail.tpl.html` to conditionally display payment method details only if available, preventing UI issues.
https://virtocommerce.atlassian.net/browse/VCST-2621
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.841.0-pr-444-37db.zip

VCST-2621: Small fix and refactoring

---

samples/VirtoCommerce.OrdersModule2.Web/Scripts/order2.js
samples/VirtoCommerce.OrdersModule2.Web/VirtoCommerce.OrdersModule2.Web.csproj
samples/VirtoCommerce.OrdersModule2.Web/package-lock.json
samples/VirtoCommerce.OrdersModule2.Web/package.json
samples/VirtoCommerce.OrdersModule2.Web/webpack.config.js
src/VirtoCommerce.OrdersModule.Core/VirtoCommerce.OrdersModule.Core.csproj
src/VirtoCommerce.OrdersModule.Data.MySql/VirtoCommerce.OrdersModule.Data.MySql.csproj
src/VirtoCommerce.OrdersModule.Data.PostgreSql/VirtoCommerce.OrdersModule.Data.PostgreSql.csproj
src/VirtoCommerce.OrdersModule.Data.SqlServer/VirtoCommerce.OrdersModule.Data.SqlServer.csproj
src/VirtoCommerce.OrdersModule.Data/VirtoCommerce.OrdersModule.Data.csproj
src/VirtoCommerce.OrdersModule.Web/Scripts/order.js
src/VirtoCommerce.OrdersModule.Web/module.manifest
src/VirtoCommerce.OrdersModule.Web/package-lock.json
src/VirtoCommerce.OrdersModule.Web/package.json
src/VirtoCommerce.OrdersModule.Web/webpack.config.js
tests/VirtoCommerce.OrdersModule.Tests/VirtoCommerce.OrdersModule.Tests.csproj

fix: Prevent loading stale .html templates by packing them into dist\app.js. Development mode will still read the HTML file from disk. Replaces custom $compile with dynamicTemplateService.ensureTemplateLoaded
https://virtocommerce.atlassian.net/browse/VCST-3295
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.852.0-pr-459-a3e1.zip

VCST-3343: Prevent loading stale .html templates

---

src/VirtoCommerce.OrdersModule.Data/Repositories/OrderRepository.cs

fix: Mark orphaned Order Entity records that no longer have a parent as Deleted. It resolves breaking changes in EF Core 7.0 (EF7) when EF Core will not automatically delete orphans when all FKs are nullable. https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#orphaned-dependents-of-optional-relationships-are-not-automatically-deleted
https://virtocommerce.atlassian.net/browse/VCST-3962
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.858.0-pr-466-bf09.zip

VCST-3962: Delete orphaned entities

---

src/VirtoCommerce.OrdersModule.Core/Model/Capture.cs
src/VirtoCommerce.OrdersModule.Core/Model/Refund.cs
src/VirtoCommerce.OrdersModule.Data/Handlers/LogChangesOrderChangedEventHandler.cs

feat:  Enhance Capture and Refund classes with auditable fields.
https://virtocommerce.atlassian.net/browse/VCST-3963
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.860.0-pr-470-1475.zip

VCST-3963: Enhance Capture and Refund classes with auditable fields
